name: apotek_kita
description: "Aplikasi mobile ApoteKita untuk memudahkan pengguna mencari informasi obat, melakukan pemesanan, dan mengelola pembelian obat."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/logo/K.svg
    - assets/logo/Plus.svg
